version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "latest"

python:
  install:
    - method: pip
      path: .
    - requirements: requirements/docs.txt # Then install doc-specific dependencies

sphinx:
  configuration: doc/source/conf.py
